### ISSUE TITLE
Initialize WPPF phases and materials from Material object

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrd#101]
#100 is a nice improvement, and we can now initialize most of the WPPF classes with data rather than file names.

Although we can now initialize the phases with a phase object directly (as is done [here](https://github.com/HEXRD/hexrd/commit/3aa726ab40f13c18b0621784464cca1fa33fb706#diff-c142f9d2dde3f2f20b5a293b8380cf5fR1495-R1499)), these phase objects and their material objects require a material file in order for them to be created (such as [here](https://github.com/HEXRD/hexrd/blob/3aa726ab40f13c18b0621784464cca1fa33fb706/hexrd/WPPF.py#L1179-L1181)).

In hexrdgui, we already have the [Material](https://github.com/HEXRD/hexrd/blob/3aa726ab40f13c18b0621784464cca1fa33fb706/hexrd/material.py#L76) object loaded in memory. It would be nice if we could instantiate the WPPF phases and material objects with this material object.

Instead, for now, it looks like we will need to write out the material that is loaded in memory to a file in a temporary directory, and then provide the file path to the WPPF phases classes so it can read it back into memory.

Note: we cannot use the original material file for this because the user may have edited the material settings without writing out the new material.

**Comment by saransh13** [comment]
I can edit the WPPF to also accept a list of material objects. Would that be acceptable?

**Comment by psavery** [comment]
Yep! I think that would be good! If they are [`hexrd.material.Material`](https://github.com/HEXRD/hexrd/blob/3aa726ab40f13c18b0621784464cca1fa33fb706/hexrd/material.py#L76) objects.

**Comment by saransh13** [comment]
The `WPPF.Materials_LeBail` is just a stripped down version of the `materials.Materials` class. This is done to keep the class lightweight. The spectrum fitting can be computationally heavy and this leads to a considerable speedup. So my plan is to take the information from `materials.Materials` class and just initialize the `WPPF.Materials_LeBail` and eventually the `WPPF.Phases_LeBail` class.
