### ISSUE TITLE
Need to reinstate HEDMInstrument init from single argument

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#11]
the direct init from the instrument YAML spec (not the experiment config) is a very useful feature, and I'd like to reinstate that in the case of a single positional argument.  You want to tackle this @donald-e-boyce, or should I?

**Comment by donald-e-boyce** [comment]
Yes, I can do that. Marcus wanted that too since much of the GUI is based
on that model.

**Comment by joelvbernier** [comment]
yeah, I am writing a calibration script for CHESS right now, and it would make my life easier.  You should be able to copy the _init_ wholesale from master...  although I thought I say you modifying property initialization away from the _prop/@propery def prop(self): model?

**Comment by psavery** [comment]
I think I have implemented some of that in [this file](https://github.com/HEXRD/hexrdgui/pull/316/commits/4389150c3a06cf378fec386ac2c3a39f46894cb1#diff-6bec66f4ec6817fd88b4756dcb43ce3c) (part of hexrd/hexrdgui#316), by the way. Let me know if we should move (and possibly generalize) some of that into hexrd.

**Comment by joelvbernier** [comment]
This is currently working in master as of [v0.7.5](https://github.com/HEXRD/hexrd/releases/tag/v0.7.5).
