### ISSUE TITLE
https://anaconda.org/HEXRD/hexrd  missing fabio as a requirement

### ISSUE THREAD

**Issue by jj-umn** [HEXRD/hexrd#110]
~/miniconda3/bin/conda create --debug -y --quiet --override-channels --channel iuc --channel conda-forge --channel bioconda --channel defaults --channel hexrd --name __hexrd@0.7.11 hexrd=0.7.11

hexrd --help
...
  File "/Users/jj/miniconda3/envs/__hexrd@0.7.11/lib/python3.8/site-packages/hexrd/imageseries/load/imagefiles.py", line 15, in <module>
    import fabio
ModuleNotFoundError: No module named 'fabio'

This works after 'pip install fabio'

**Comment by cjh1** [comment]
Thanks @jj-umn for reporting this, we will update the recipe to include fabio.

**Comment by cjh1** [comment]
@jj-umn This is now fixed in master. If you install using the prerelease channel `hexrd/label/hexrd-prerelease` you can pick up the change.

**Comment by joelvbernier** [comment]
Thanks for spotting this @jj-umn -- we are compiling tutorial resources presently in order to put together serveral workflow demos.  If I might ask, is you interest primarily 3DXRD/HEDM, powder diffraction, Laue, or general?

**Comment by jj-umn** [comment]
@joelvbernier   I'm  helping with a NSF grant project (AWARD:11140-VINALS-NSF-CON000000087734-3002)  for building a gateway server using the galaxy framework to analyze HEDM data.  The plan is to develop galaxy workflows for the Cornell High Energy Synchrotron Source '[CHESS](https://www.chess.cornell.edu)' pipeline. 

The Galaxy framework ( [https://galaxyproject.org](https://galaxyproject.org)  [https://github.com/galaxyproject](https://github.com/galaxyproject) ) provides a web interface for running command line applications in interconnected workflows.  

I'm primarily the Galaxy developer for the grant.   Most of my software work in the past 20 years has been related to genomic sequencing and mass spec proteomics.   

It would probably be good to have the CHESS group involved with tutorials. 
Thanks,

JJ
