### ISSUE TITLE
Add pycifrw to conda requirements

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrd#112]
It's currently a requirement in the setup.py [here](https://github.com/HEXRD/hexrd/blob/700d4aea98621e017bf2bea3c5110faa59b4ef0a/setup.py#L15).

I think we need to add it [here](https://github.com/HEXRD/hexrd/blob/700d4aea98621e017bf2bea3c5110faa59b4ef0a/conda.recipe/meta.yaml#L24) also.

**Comment by cjh1** [comment]
Fixed in #113
