### ISSUE TITLE
WPPF errors

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#129]
Looks like WPPF is refining a lattice parameter even when I check the "vary" box off.  You should check how the flags are being captured by the GUI (may need an issue there).

**Comment by joelvbernier** [comment]
@saransh13 did this get fixed?  If so, which PR?

**Comment by saransh13** [comment]
Don't think this has been fixed yet. I'm looking into it.

**Comment by joelvbernier** [comment]
Nudging you on this @saransh13

**Comment by joelvbernier** [comment]
This issue has been resolved as of #285 (probably earlier even).
