### ISSUE TITLE
feature branch cleanup

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#130]
@cjh1, @psavery, @johnkit, and @saransh13 -- can you take a look at any old feature branches of yours to prune off of hexrd?  We've accumulated quite a few!

**Comment by cjh1** [comment]
Done on my end

**Comment by saransh13** [comment]
I just have one. Still ned to finish some work before merging it.

**Comment by joelvbernier** [comment]
Yeah, this is only for stale branches.
