### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrd#133]
There is some error in the `hexrd` installation. Not sure where this is originating. The installation goes fine on my Mac.

`gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/opt/sqlite/include -I/usr/local/opt/sqlite/include -I/Users/runner/hostedtoolcache/Python/3.8.6/x64/include/python3.8 -c src/lib/lex.yy.c -o build/temp.macosx-10.14-x86_64-3.8/src/lib/lex.yy.o
133
    star.l:111:28: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
134
                     while ( p = strchr( p, '\''))
135
                             ~~^~~~~~~~~~~~~~~~~~
136
    star.l:111:28: note: place parentheses around the assignment to silence this warning
137
                     while ( p = strchr( p, '\''))
138
                               ^
139
                             (                   )
140
    star.l:111:28: note: use '==' to turn this assignment into an equality comparison
141
                     while ( p = strchr( p, '\''))
142
                               ^
143
                               ==
144
    star.l:136:28: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
145
                     while ( p = strchr( p, '\"'))
146
                             ~~^~~~~~~~~~~~~~~~~~
147
    star.l:136:28: note: place parentheses around the assignment to silence this warning
148
                     while ( p = strchr( p, '\"'))
149
                               ^
150
                             (                   )
151
    star.l:136:28: note: use '==' to turn this assignment into an equality comparison
152
                     while ( p = strchr( p, '\"'))
153
                               ^
154
                               ==
155
    star.l:117:24: warning: comparison of integers of different signs: 'int' and 'yy_size_t' (aka 'unsigned long') [-Wsign-compare]
156
                           yyless( i );
157
                           ^~~~~~~~~~~
158
    lex.yy.c:205:9: note: expanded from macro 'yyless'
159
            YY_LESS_LINENO(yyless_macro_arg);\
160
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
161
    lex.yy.c:187:36: note: expanded from macro 'YY_LESS_LINENO'
162
                    for ( yyl = n; yyl < yyleng; ++yyl )\
163
                                   ~~~ ^ ~~~~~~
164
    star.l:142:24: warning: comparison of integers of different signs: 'int' and 'yy_size_t' (aka 'unsigned long') [-Wsign-compare]
165
                           yyless( i );
166
                           ^~~~~~~~~~~
167
    lex.yy.c:205:9: note: expanded from macro 'yyless'
168
            YY_LESS_LINENO(yyless_macro_arg);\
169
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
170
    lex.yy.c:187:36: note: expanded from macro 'YY_LESS_LINENO'
171
                    for ( yyl = n; yyl < yyleng; ++yyl )\
172
                                   ~~~ ^ ~~~~~~
173
    lex.yy.c:1602:40: error: implicit declaration of function 'isatty' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
174
            b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
175
                                           ^
176
    4 warnings and 1 error generated.
177
    error: command 'gcc' failed with exit status 1
178
    ----------------------------------------
179
ERROR: Command errored out with exit status 1: /Users/runner/hostedtoolcache/Python/3.8.6/x64/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-_692spv7/pycifrw/setup.py'"'"'; __file__='"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-_692spv7/pycifrw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-record-bvpl9k4k/install-record.txt --single-version-externally-managed --compile --install-headers /Users/runner/hostedtoolcache/Python/3.8.6/x64/include/python3.8/pycifrw Check the logs for full command output.`

**Comment by cjh1** [comment]
This is on linux?

**Comment by saransh13** [comment]
On Mac. Error is from continuous integration.

**Comment by cjh1** [comment]
OK, thanks, I can take a look.
