### ISSUE TITLE
Need to add lmfit dependency

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#143]
conda-build is currently failing on master.  One reason is lmfit; seems like this is a hard req now.  Is there a specific version/channel we need to pin to @saransh13?

**Comment by joelvbernier** [comment]
Nudging you @cjh1 and @saransh13 ...

**Comment by cjh1** [comment]
I will take care of this.

**Comment by joelvbernier** [comment]
Thanks @cjh1

**Comment by cjh1** [comment]
Closing this, should now be included.
