### ISSUE TITLE
Warning running find-orientations and fit-grains on Windows

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#155]
I am getting the following during both the fiber generation, the orientation scoring, and grain fitting -- all using `map`:
```
C:\Users\berni\miniconda3\envs\hexrd_0.8\lib\runpy.py:127: RuntimeWarning: 'hexrd.cli.main' found in sys.modules after import of package 'hexrd.cli', but prior to execution of 'hexrd.cli.main'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
```
Thoughts @psavery and/or @cjh1?

**Comment by cjh1** [comment]
I think removing [this](https://github.com/HEXRD/hexrd/blob/master/hexrd/cli/__init__.py#L11) line will resolve it.

**Comment by cjh1** [comment]
I don't see this warning when running the hexrd cli on Windows from a conda install. When are you seeing this?

**Comment by joelvbernier** [comment]
conda package install on Windows 10 as well.  @donald-e-boyce, do you think that we can safely remove [this](https://github.com/HEXRD/hexrd/blob/master/hexrd/cli/__init__.py#L11) line?

**Comment by donald-e-boyce** [comment]
I think you can safely remove it.

**Comment by cjh1** [comment]
@joelvbernier I am still not see this even with hexrd installed with pip. What is the hexrd invocation you are using?

**Comment by joelvbernier** [comment]
@cjh1 -- running the CLI from a local install in dev mode on Windows 10 (Anaconda Powershell).  Each process echos back the warning.

**Comment by cjh1** [comment]
So you get it if you run just `hexrd --help`?

**Comment by joelvbernier** [comment]
I think this has been resolved.
