### ISSUE TITLE
Restore "--version, -v" to hexrd CLI

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#166]
Not sure when this got dropped; @cjh1 can you reinstate/add this CLI flag?  Did this get killed when we dropped versioneer?

**Comment by joelvbernier** [comment]
@cjh1 -- can you help resolve this?  Probably need to modify the `init.py` in the hexrd package?

**Comment by joelvbernier** [comment]
bumping up the priority on this one...

**Comment by psavery** [comment]
Looks like we might be able to add an argparse argument around [here](https://github.com/HEXRD/hexrd/blob/bf0d30c57c7497f99b8d8402a5261f104fa17e29/hexrd/cli/main.py#L33) like this:
```
p.add_argument('--version', action='version', version='%(prog)s 2.0')
```

As per [this documentation](https://docs.python.org/dev/library/argparse.html#action). We'll just need to make sure the right version gets printed out...

**Comment by cjh1** [comment]
@psavery @joelvbernier I can take a look at this.
