### ISSUE TITLE
Capture logging output to dialog

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#167]
We need to capture the logging output for the CLI workflow to a dialog, or otherwise make modifications so that we can expose computation status in the GUI.

**Comment by joelvbernier** [comment]
I'd say this is half done; we still need to feed more information to the `logger` class internally.  The GUI, however, does have a container for the output as of https://github.com/HEXRD/hexrdgui/pull/959

**Comment by psavery** [comment]
I think this is now done as of https://github.com/HEXRD/hexrdgui/pull/959 and #350. Feel free to reopen if needed.

**Comment by psavery** [comment]
Nevermind. I thought that #350 was closed because it was fixed. But it was closed as a duplicate for this one. I'm going to reopen #350, though, and track this in there.
