### ISSUE TITLE
error starting hexrd gui

### ISSUE THREAD

**Issue by hsheng94** [HEXRD/hexrd#176]
I just installed hexrd on my mac and the version is hexrd                     0.7.10          py38h39e3cac_14 . I wanted to start hexrd gui but got the following message. I installed through conda but seem some packages are missing. Could you help check what other dependencies I need to install? Thanks!

\$ hexrd gui 
Traceback (most recent call last):
  File "/Users/hao_sheng/anaconda/envs/hexrd2021/bin/hexrd", line 11, in <module>
    sys.exit(main())
  File "/Users/hao_sheng/anaconda/envs/hexrd2021/lib/python3.8/site-packages/hexrd/cli/main.py", line 75, in main
    args.func(args, p)
  File "/Users/hao_sheng/anaconda/envs/hexrd2021/lib/python3.8/site-packages/hexrd/cli/gui.py", line 36, in execute
    from hexrd.wx import mainapp
ModuleNotFoundError: No module named 'hexrd.wx'

**Comment by cjh1** [comment]
Hi @hsheng94, Did you follow [these](https://github.com/HEXRD/hexrdgui/blob/master/README.md) instructions? For a conda install you need to run the following:

```
conda install -c HEXRD python=3.8.4
conda install -c HEXRD -c anaconda -c conda-forge hexrdgui
```

Let us know if that works for you.

**Comment by joelvbernier** [comment]
A few notes:

First, that is a very old conda package at this point.  I would recommend building from the latest conda package using the `prerelease` label as documented https://github.com/HEXRD/hexrdgui#conda-prerelease.  Alternatively, you can download and install the conda packages for [hexrd](https://anaconda.org/HEXRD/hexrd/files)and [hexrdgui](https://anaconda.org/HEXRD/hexrdgui/files) directly.

Also, the command line link to the gui script is no longer under the hexrd CLI (`hexrd gui`) but is its own package, called via `hexrdgui`.

Lastly, as far as the pre-built binaries for Mac OS are concerned: we have figured out the notarization process required by Mac OS >=10.15 and will be pushing a new [release](https://github.com/HEXRD/hexrdgui/tags) tomorrow (0.8.2).

**Comment by joelvbernier** [comment]
@hsheng94 -- were you able to resolve your problem?

**Comment by joelvbernier** [comment]
This issue -- if still applicable (I don't thik it is) -- should go on hexrdgui.
