### ISSUE TITLE
Two instrument.py files

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrd#18]
One [here](https://github.com/HEXRD/hexrd/blob/master/hexrd/instrument.py) and one [here](https://github.com/HEXRD/hexrd/blob/master/hexrd/instrument/instrument.py).

It looks like if I import `HEDMInstrument`, it imports the one inside `hexrd/instrument/instrument.py`. Is one of these `instrument.py` files destined for removal?

```
>>> import inspect
>>> from hexrd.instrument import HEDMInstrument
>>> inspect.getfile(HEDMInstrument)
'/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/instrument/instrument.py'
```

**Comment by joelvbernier** [comment]
This was the result of a bad merge.  It has been fixed.
