### ISSUE TITLE
Consider modifying the number of default exclusions for materials

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrd#225]
Should we consider increasing the number of default exclusions for materials?

For instance, for ruby from hexrdgui:
```python
>>> from hexrd.material import Material
>>> mat = Material('ruby', 'materials.h5')
>>> mat.planeData.exclusions
array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])
```

Results in:
![image](https://user-images.githubusercontent.com/9558430/111412141-d66d1480-86a9-11eb-87dc-a1d506f8612b.png)

in hexrdgui, at program start-up (if ruby powder overlays are visible).

This is particularly painful if you try to run something like generating eta omega maps, and you forget to modify the exclusions (because it will take a very long time, and many more hkls will be used than typically needed).

Should we modify the [default exclusions function](https://github.com/HEXRD/hexrd/blob/4736bcbbb9f0fc3cdeccc00528e734de6407cc03/hexrd/material.py#L280) so that fewer hkls are included?

**Comment by joelvbernier** [comment]
I'd say if the default should be all excluded but the first 5 reflections.  The exclusions set technically _can_ be preserved unless the space group is changed (in general).
