### ISSUE TITLE
hexrd/unitcell.py UnboundLocalError: local variable 'om' referenced before assignment line: 447

### ISSUE THREAD

**Issue by jj-umn** [HEXRD/hexrd#274]
>>> material_file = '/Users/jj/Downloads/mp-46_Ti.cif'
>>> from hexrd import material
>>> from hexrd.material import Material
>>> mat = Material('Ti2',material_file=material_file)
/Users/jj/miniconda3/envs/__hexrd@0.8.4/lib/python3.8/site-packages/hexrd/material.py:493: UserWarning: Debye-Waller factors not present.                 setting to same values for all atoms.
  warn('Debye-Waller factors not present. \
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jj/miniconda3/envs/__hexrd@0.8.4/lib/python3.8/site-packages/hexrd/material.py", line 197, in __init__
    self._newUnitcell()
  File "/Users/jj/miniconda3/envs/__hexrd@0.8.4/lib/python3.8/site-packages/hexrd/material.py", line 238, in _newUnitcell
    self._unitcell = unitcell.unitcell(
  File "/Users/jj/miniconda3/envs/__hexrd@0.8.4/lib/python3.8/site-packages/hexrd/unitcell.py", line 61, in __init__
    self.sgnum = sgnum
  File "/Users/jj/miniconda3/envs/__hexrd@0.8.4/lib/python3.8/site-packages/hexrd/unitcell.py", line 1473, in sgnum
    self.GenerateCartesianPGSym()
  File "/Users/jj/miniconda3/envs/__hexrd@0.8.4/lib/python3.8/site-packages/hexrd/unitcell.py", line 447, in GenerateCartesianPGSym
    ss = np.dot(om, np.dot(s, om.T))
UnboundLocalError: local variable 'om' referenced before assignment

**Comment by joelvbernier** [comment]
Updating to the latest conda package should fix this.  Seems like you are on an older version?

**Comment by joelvbernier** [comment]
@saransh13 -- can you take a look at this?

**Comment by joelvbernier** [comment]
@jj-umn -- can you attach the CIF file you are trying to import here?

**Comment by jj-umn** [comment]
File downloaded from:   https://materialsproject.org/materials/mp-46/


```
# generated using pymatgen
data_Ti
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   2.93381380
_cell_length_b   2.93381380
_cell_length_c   4.65700900
_cell_angle_alpha   90.00000000
_cell_angle_beta   90.00000000
_cell_angle_gamma   120.00000000
_symmetry_Int_Tables_number   1
_chemical_formula_structural   Ti
_chemical_formula_sum   Ti2
_cell_volume   34.71385164
_cell_formula_units_Z   2
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Ti  Ti0  1  0.66666667  0.33333333  0.75000000  1.0
  Ti  Ti1  1  0.33333333  0.66666667  0.25000000  1.0

```

**Comment by saransh13** [comment]
Ok I think I know where the error is coming from. There is an. uninitialized matrix specific to the point group `c1`. I'll push a fix to this soon.
@jj-umn I think the cif file has Ti as space group 1 most likely. I don't know if that was intentional.

**Comment by jj-umn** [comment]
@saransh13   **_symmetry_space_group_name_H-M   'P 1'**  was a field in the CIF file.  
Does **H-M   'P 1'** then imply sgnum=1 and does Material set the sgnum from the CIF file?

I'm new to this field, so I confess to having no idea as to the expected space group for a material.  
Perhaps I was supposed to set some value in  https://materialsproject.org/materials/mp-46/

**Comment by jj-umn** [comment]
@saransh13   If I download the json file from  https://materialsproject.org/materials/mp-46/
There is a spacegroup included: 
"spacegroup": {"symprec": 0.1, "source": "spglib", "symbol": "P6_3/mmc", "number": 194, "point_group": "6/mmm", "crystal_system": "hexagonal", "hall": "-P 6c 2c"},

Are their CIF files not useful for a hexrd Material?

**Comment by joelvbernier** [comment]
CIF is a pretty sloppy format, so it depends on the format and the source.  There are lots of equivalent options.  We can add a simple HCP metal (say Ti) to the default materials as a template in the meantime.  Looks like @saransh13 will push a fix for your example ASAP.  Thanks for raising the issue!

**Comment by saransh13** [comment]
@jj-umn Yes, H-M P1 is space group 1 in hermann mauguin notation. Ti crystal is space group 194, which is correct in the json file. You should use the symmetrized one from the list of the CIF files. That one has the correct symmetry groups. 

![Screen Shot 2021-05-27 at 4 05 29 PM](https://user-images.githubusercontent.com/15834451/119907549-6084f500-bf05-11eb-844d-83587e674106.png)

The error you got was an actual bug in hexrd Materials, which I'll push a fix to soon. Once that is patched, hexrd should work for the CIF file you supplied. However, space group 1 for Ti will result in incorrect properties for Ti.

**Comment by saransh13** [comment]
PR #276 should fix it. Tested it with the CIF file posted above.

**Comment by jj-umn** [comment]
Thanks for the quick response and for the patience in explaining to a novice.

**Comment by joelvbernier** [comment]
For your reference, I have attached an hdf5 archive with generic alpha Titanium in it (HCP).
[alpha-Ti_material.h5.zip](https://github.com/HEXRD/hexrd/files/6557377/alpha-Ti_material.h5.zip)
