### ISSUE TITLE
Getting Developer Mode Running

### ISSUE THREAD

**Issue by darrencpagan** [HEXRD/hexrd#278]
After installing hexrd following the instructions in the README, I got the error:

```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```

Looked online and found its and issue with the numpy installation, the command
```
pip install numpy --upgrade
```
got things running.

**Comment by joelvbernier** [comment]
I would suggest not using `pip` packages in general, as there have been segfault issues with its NumPy recently (at least on Mac).  The `conda` packages seem more stable w.r.t. interoperability.

If you follow the instructions [here](https://github.com/HEXRD/hexrd#conda), it installs all of the package dependencies from `conda`, and only uses `pip` (using the `--no-build-isolation --no-deps -U -e` flags) to set up the local links to `hexrd` (and/or `hexrdgui`, analogously described [here](https://github.com/HEXRD/hexrdgui#conda)).  That will give you a developer mode with all `conda`-installed dependencies, which are the same versions in the `conda` packages of `hexrd` and `hexrdgui`.

**Comment by darrencpagan** [comment]
I followed the instructions you linked to when I ran into the issue,

**Comment by joelvbernier** [comment]
@psavery -- can you take a look at this?

**Comment by joelvbernier** [comment]
I am not having an issues on Mac, Windows, or Linux setting up dev mode by doing
### Mac/Linux
```
> CONDA_BUILD=1
> pip install --no-build-isolation --no-deps -U -e hexrd
```
### Windows
```
> set CONDA_BUILD=1
> pip install --no-build-isolation --no-deps -U -e hexrd
```
Do you have steps to recreate the issue on whatever platform is giving you the problem?

**Comment by joelvbernier** [comment]
Closing this issue, as I can't recreate any problems with running in developermode (`conda` env linked to repo using `pip`).  Can re-open if a new issue comes up.
