### ISSUE TITLE
Handling array-like panel buffers (masks) in instrument config write

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#28]
The current output method `instrument.HEDMInstrument().write_config()` is _not_ appropriate if the panel buffers are array-like.  There are two possible fixes, and perhaps we should implement both.
1. Add an HDF5 instrument config format, and store the buffer as a dataset (numpy ndarray)
2. In the case of array-like panel buffer, add a trigger in the YAML output to load buffer from a flat npy file that gets auto-generated.

Thoughts @cryos @psavery @cjh1 @donald-e-boyce ?

**Comment by cjh1** [comment]
If we go down the route of using HDF5 I would suggest that we keep the same yaml format and write the yaml file as a dataset inside the HDF5, rather than separating it out.

**Comment by joelvbernier** [comment]
@donald-e-boyce -- I'm thinking in YAML context, we just add a trigger.  Then if the `panel_buffer` attribute has `ndim = 2`, it will trigger the `write_config` method to save an npy file for the buffer/mask and put a trigger in the corresponding section in the YAML file.  Then we modify the `__init__` method to handle the triggered load-from-file case.  SHhould be analogous to what you did in the `image-files` adapter in `imageseries`, yes?

**Comment by donald-e-boyce** [comment]
To sort of answer your question, here is how the trigger worked in yaml.

```
meta:
  omega: "! load-numpy-array omegas.npy"
```

If any string-valued item begins with "! ", then another function is called
to process that. This is how the original frame-cache metadata was written.
The actual frame data was in an npz, but the metadata was in a yaml.

**Comment by joelvbernier** [comment]
I think that the YAML + trigger approach will be best for now.  @donald-e-boyce do you have the bandwidth to do this?

**Comment by cjh1** [comment]
YAML does actually support a binary type, this is probably the way to go. Otherwise we run into issues passing around the location of the instrument config so that we know where to load the npy file from. I will see how it performs.

**Comment by cjh1** [comment]
Scratch that, there is a restriction on the length :-1:

**Comment by joelvbernier** [comment]
So that either leaves several choices:

1. the somewhat unsavory two-file option with a trigger to point to and load the .npy mask(s)
2. just proclude the `write_config()` method from appending an array_like mask (user can load it themselves later)
3. make an HDF5 format for the instrument config

Well, 2 is easiest...

**Comment by cjh1** [comment]
I will take a look another look at 1.
