### ISSUE TITLE
configuration yaml not saving for dexelas in 0.8.6

### ISSUE THREAD

**Issue by kenygren** [HEXRD/hexrd#283]
@joelvbernier When saving the configuration yaml, the dexela values are not populated - instead a generic ge yaml is generated. I do not know in which version this started but Kate suggests it may be related to issues that users are having with calibrations.

**Comment by joelvbernier** [comment]
I have not been able to replicate this behavior -- can you provide the exact steps and versions of `hexrdgui` and `hexrd` that you are seeing this?

**Comment by joelvbernier** [comment]
Any updates on this @kenygren?

**Comment by kenygren** [comment]
Cannot reproduce it at the moment so we can close the issue.


Kelly Elizabeth Nygren, Ph.D.

Cornell High Energy Synchrotron Source

Cornell University

________________________________

**Comment by psavery** [comment]
Closing. Please re-open if the issue is encountered again.
