### ISSUE TITLE
threshold in instrument.extract_polar_maps no longer functions

### ISSUE THREAD

**Issue by darrencpagan** [HEXRD/hexrd#284]
The threshold specified in the experiment config file

```
find-orientations.orientation-maps.threshold 
```

no longer does anything. The variable was traced to the threshold input in instrument.extract_polar_maps which no longer is used. This variable should be removed from the config file.

**Comment by joelvbernier** [comment]
@psavery did this get clobbered?

**Comment by joelvbernier** [comment]
@darrencpagan -- that threshold is getting applied here:
https://github.com/HEXRD/hexrd/blob/ab052ce700653a88669538bb8a2538ae0140752f/hexrd/instrument.py#L3695-L3699

**Comment by joelvbernier** [comment]
Closing this, as it seem that it is just a matter of looking at a version of hexrd prior to PR #227
