### ISSUE TITLE
"RuntimeError" with "0 reflections"

### ISSUE THREAD

**Issue by georgejoe018** [HEXRD/hexrd#291]
I am trying to run a grain fit using the HEXRDGUI and run through an indexing beforehand. I am setting a threshold and have calibrated the overlays. When I go to run a grain fit after indexing, there is another window that pops up about setting specific step size. I press okay for that window with the default settings. After running for some time, an error pops up: 

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/nfs/chess/sw/anaconda3_id1a3/envs/hexrd_0.8.6/lib/python3.8/site-packages/hexrd/fitgrains.py", line 192, in fit_grain_FF_reduced
    completeness = num_refl_valid / float(num_refl_tot)
ZeroDivisionError: float division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/chess/sw/anaconda3_id1a3/envs/hexrd_0.8.6/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/nfs/chess/sw/anaconda3_id1a3/envs/hexrd_0.8.6/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/nfs/chess/sw/anaconda3_id1a3/envs/hexrd_0.8.6/lib/python3.8/site-packages/hexrd/fitgrains.py", line 194, in fit_grain_FF_reduced
    raise RuntimeError(
RuntimeError: simulated number of relfections is 0; check instrument config or grain parameters
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nfs/chess/sw/anaconda3_id1a3/envs/hexrd_0.8.6/lib/python3.8/site-packages/hexrd/ui/async_worker.py", line 73, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nfs/chess/sw/anaconda3_id1a3/envs/hexrd_0.8.6/lib/python3.8/site-packages/hexrd/ui/indexing/run.py", line 286, in run_fit_grains
    self.fit_grains_results = fit_grains(**kwargs)
  File "/nfs/chess/sw/anaconda3_id1a3/envs/hexrd_0.8.6/lib/python3.8/site-packages/hexrd/fitgrains.py", line 393, in fit_grains
    fit_results = pool.map(
  File "/nfs/chess/sw/anaconda3_id1a3/envs/hexrd_0.8.6/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/nfs/chess/sw/anaconda3_id1a3/envs/hexrd_0.8.6/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
RuntimeError: simulated number of relfections is 0; check instrument config or grain parameters

I am not sure what this all means whether it is there are no grains/spots at the locations or if the parameters have to be set a certain way. I have tried several different thresholds and configurations, and I still get this error output when going to fit grains. Any insight to what I could try to fix this problem would be fantastic.

**Comment by joelvbernier** [comment]
Typically this occurs if the omega (rotations) specifications on your imageseries are input incorrectly (_e.g._, too small an interval, like (0, 1) degrees, which, dependingon the space group, number of hkls selected, and orientaton could have 0 reflections).  Can you confirm that your imageseries have the proper omega metadata?

**Comment by georgejoe018** [comment]
@joelvbernier I am not totally sure what the proper omega metadata would be for the imageseries. I am working with a created material of Ti7Al. It has a space group of 194 and the lattice parameters are 2.95 A for a and 4.68 A for c. The rest of the inputs are the default settings. The data loaded in has 1445 total frames, zero empty frames, and the omega step is 0.25 starting from 0. When running the indexing, I leave all settings on default except for altering the thresholding, selecting to eta omega maps that have viable spots, and changing the clustering to FCclusterdata. When the fit grains window pops up, I use the default settings in that usually.

**Comment by joelvbernier** [comment]
There must be extra frames, since there 1440 frames at 0.25 degrees gives you 360&deg;.  **_Note that the rotation interval cannot exceed 360&deg;_**!  I suspect that this is what is going on with your data.  If you are giving it 1445 frames at 0.25 degree spacing, then you have 5 frames over 360&deg; and to the code it looks like your total rotation range is only 1.25&deg;.  Where was this measured?  You will have to double check regarding empty frames at the beginning (there is typically at least 1 at APS.).

**Comment by georgejoe018** [comment]
@joelvbernier This data was measured at the CHESS facility. I have tried to change the omega degree spacing to equal 360 degrees by changing the step size to 0.2491. This gave the same error. I have looked through the images and have not found any duplicate or empty frames within the images taken. I have also tried adding in 5 empty frames, and I get the error of 

hexrd.imageseries.omega.OmegaSeriesError: 'number of frames (1445) does not match number of wedge frames (1440)'

and then the runtime error after running an indexing with that. Could it be that there are empty frames somewhere else in the file? I looked at the first 10 and last 10 frames of the data set and there were not any empty frames and they did not seem like duplicates. Additionally, there was a point when I had the two detector data sets loaded, only data was being shown on the first detector graph. The second detector graph was not showing any data. I am not sure if this is related to why I'm getting an error or if this is a separate issue. It came after running an indexing with the omega step size altered.

**Comment by joelvbernier** [comment]
Ok -- can you point me to the raw data?  And who was your beamline scientist (I know them all)?  Also, what version of hexrd are you running?

I'll take a close look to see what is going on with your case.

**Comment by georgejoe018** [comment]
The raw data is located in /nfs/chess/raw/current/id3a/brunson-3139-a. Files with "mn" are where the data is. "mn6-1" is an example of one of the folders where the data is located. It is all the way down into the "ff" directory for any of the numbered folders. The beamline scientist was Katherine or Kate Shanks. I am running this data on version 0.8.4. It's not the newest version, but it was running more than other versions, so I stuck with it.

**Comment by joelvbernier** [comment]
I'll need more information to figure out what is going wrong -- your error is almost always due to incorrect omega specification.  This is unfortunately not encoded with the raw images, so you'll need to point me to a few things:

1. The wavelength, or equivalently energy you were using
2. Calibration data (CeO2 scans, or multiruby, ideally both)
3. The material description of the phase you are interested in and the relevant scans
4. Scan parameters (it seems like you were doing full 360°. in 1440 or 1441 steps?)

I've examined a lot of chess/dexela data, so it is likely a simple omission or error in metadata that is causing your headaches.  Also, the latest packages include many, many improvements over the older version you are using.

**Comment by joelvbernier** [comment]
PS -- I would've gotten back sooner, but my son had brain surgery in August and I was off for essentially the whole month.

**Comment by joelvbernier** [comment]
@georgejoe018 -- I'm going to close this since I haven't heard back.  If you are still having issues, we can re-open.
