### ISSUE TITLE
Extra output from findorientations.py

### ISSUE THREAD

**Issue by darrencpagan** [HEXRD/hexrd#294]
Would it be possible to adjust findorientations.py to have a keyword argument to also output the full quaternion test list (qfib) and the associated completeness values?

This would be useful output for cleaning the misorientation functionality of the grainmap/nf portion of the code?

**Comment by psavery** [comment]
Hi @darrencpagan. 

@joelvbernier can correct me if I'm wrong, but I believe these are returned from the `find_orientations()` function in the `scored_orientations` key as `test_quaternions` (qfib) and `score` (completeness). You can see where those get set [here](https://github.com/HEXRD/hexrd/blob/2b6f1445b25db30ab6007a111d0aa1bdbd023742/hexrd/findorientations.py#L810-L814). That `results` object is returned from the function.

**Comment by darrencpagan** [comment]
@psavery, you are right. I got distracted by results['qbar'] output later in the code. I'll close this.
