### ISSUE TITLE
We should remove all contents from hexrd.__init__.py

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrd#299]
We are using `hexrd` as a [namespace package](http://peak.telecommunity.com/DevCenter/setuptools#namespace-packages) for hexrd and hexrdgui. This may appear to work in dev but these files will not be installed with a system packaging tool ...

**Comment by joelvbernier** [comment]
Seems ok by me.

**Comment by joelvbernier** [comment]
@cjh1 and @psavery -- I don't think we did anything here yet.  Should we proceed?

**Comment by cjh1** [comment]
Yes, we should proceed. Its low risk.

**Comment by joelvbernier** [comment]
Blanking this causes problems firing up the GUI in develop mode, as I pointed out in #317

**Comment by cjh1** [comment]
Resolved by: #322
