### ISSUE TITLE
Save/load materials via a "materials" key in the HDF5 file

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrd#321]
In order to facilitate state saving in hexrdgui, it would be better to allow the "materials" to be part of a larger HDF5 file that contains other parts of the state of hexrdgui, including the instrument and other parts.

It would be helpful for us to modify the materials saving/loading so that we can provide the functions an h5py file or group instead of a string. This way, if we have larger `save_state()` and `load_state()` functions, these functions can pass the already-loaded h5py file/group to the materials functions to perform the saving/loading.

We will probably save the materials in `/materials` within the state file. But if we can hand the materials saving/loading functions an h5py group, we can potentially just give them an h5py group that is already at `/materials`, so it can just go ahead and perform the saving/loading and not care about where in the file it is located. This would make it so we don't have to change the materials saving/loading functions in case we end up loading materials from a different part of the HDF5 file.

**Comment by cjh1** [comment]
Is there something in addition to what has been added in #310 that we need?

**Comment by psavery** [comment]
@cjh1 No I think that will work. We didn't realize it had already been done in #310.
