### ISSUE TITLE
Save tThWidth attribute on PlaneData object on material

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#327]
Currently this attribute is not saved; @saransh13 can you modify material to save this setting along with exclusions?

**Comment by psavery** [comment]
We discussed this today. Fixing this will also allow it to be saved in the state of hexrdgui.

**Comment by joelvbernier** [comment]
Looks like we need to fixe this to do the state save properly @saransh13.

**Comment by psavery** [comment]
I believe this was fixed in #387.
