### ISSUE TITLE
Need raw import option for imageseries

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#339]
@donald-e-boyce -- I know we've discussed this before, but there is now a more pressing need.

We need a "raw" format adapter for `ImageSeries` that allows users to load image formats not supported by `fabio`.  [ImageJ handles this nicely](https://imagej.nih.gov/ij/docs/menus/file.html#import).  The arguments must at least include:  
- pixel dtype
- shape (number of images, rows, cols)
- byte offset to first image
- byte gap between images (if any)
- image path(s)
Should be pretty straightforward, yes?
![image](https://user-images.githubusercontent.com/1154130/137396602-29b0f7d0-0215-4d89-b69a-9abd37dbe4f9.png)

**Comment by joelvbernier** [comment]
Might have to fake it or ask Andrew for a smaller scan, because the one he has is HUUUUUGE.

**Comment by donald-e-boyce** [comment]
Joel,

I am using ruby data to work through an example. Some questions:

* You say your example is GE saved as int32, blank 8192 header. The
ruby dtype is uint16 and image shape is 2048x2048. So is the data
saved in a GE output file or has it been read and saved as a binary
file of int32?
* And the 8192 header means 8192 bytes?

Don

**Comment by joelvbernier** [comment]
@donald-e-boyce 

Yes, at APS if they sum GE images in software, it gets recast as `int32` from `uint16`; they tack on an empty 8192 byte header for compatibility with some reader software they have.  But in general, users could axe the empty header and we would still want to be able to load (hence why we need to specify the header length in bytes).  The example scans I have access to are enormous, but we can fake a version with a background-subtracted GE scan from [here](https://drive.google.com/file/d/1nkS4rm9xirTDho92K08GT_syUk_f8NAC/view?usp=sharing).

**Comment by donald-e-boyce** [comment]
Is that the same as the RUBY_4537 I already have? In any case, I have a
good start and would like to discuss a couple things with you if you have
time soon.

Don

**Comment by joelvbernier** [comment]
Yes -- I am happy to make an int32 version for you and upload; I was just going to

1. make a median background (first 120 frames)
2. cast that and RUBY_4537 to `int32`
3. do the subtraction
4. write out binary file with empty 8192 header

That is essentially the APS datatype we are dealing with that `fabio` won't recognize.  Of course, there could be other formats as well, but this particular one has established use case.

**Comment by joelvbernier** [comment]
Recall that the "real" ge format that `fabio` recognizes has a 8192-byte header with actual useful metadata in it, including image shape, number of images and pixel dtype.  The "bastardized" get format has an 8192-byte header of all zeros (`fabio` checks for a header starting with some number of zeros in this case...) with a shape of (2048, 2048) and pixel dtype of `uint16`.  The format in question (_e.g._, used for summed GE images at APS) is 

- 8192-byte header (or more accurately, the first image pixel starts at position 8193)
- stream of `nframes*4194304` 4-byte integers (interpreted as an `(nframes, 2048, 2048)` array with `dtype=int32`

**Comment by joelvbernier** [comment]
@bnmajor and @donald-e-boyce -- where are with with respect to integrating this with `hexrd` and `hexrdgui`?

**Comment by donald-e-boyce** [comment]
This weekend, I can set up an imageseries adapter for the raw imageseries.
It will be somewhat limited relative to the other adapters in there. For
example, it go to an arbitrary frame---it can only go to frame 0 or to the
next frame in sequence. Also, it won't have a save format. And it will need
more development in the future as new users come up with new formats.
Still, it will be useful for loading and saving to hdf5 or a frame cache
and can be extended as needed.

If I do that, then Brianna can focus on the GUI part.

Don

**Comment by bnmajor** [comment]
@joelvbernier - Don shared a script with me that he has working for raw images. I can use this to rough in the GUI portion of things and when the adapter is available I can connect everything.

**Comment by joelvbernier** [comment]
Merged #388 in hexrd; I think this is what you need :-)
