### ISSUE TITLE
Handling '-1' in H5 files generated by Eiger detector

### ISSUE THREAD

**Issue by agshabalin** [HEXRD/hexrd#355]
Hello, 

I'm trying to load 2D images from h5 files produced by Eiger detector. This detector assigns '-1' value to the pixels between the detector pads and the bad pixels. But when I open such h5 files with imageseries the data type is automatically specified as 'uint32' so those negative values become 4294967295. I need them to be 0, ideally without the need for searching&replacing in every image. Would it be possible to include the support of such *h5 files into imageseries?
Thank you!

**MY CODE:**
import numpy, hexrd, os, yaml
from hexrd import imageseries

pars = {'image-files':{'directory':'./',
                    'files':'pencil_0028_master.h5'},
     'options':{'empty frames': 0,'max-frames': 0},
     'meta':{'omega': 0}
    }
with open('config.yml', 'w') as f:
        yaml.dump(pars, f)

imgs = imageseries.open('config.yml', 'image-files')
print(f'imgs min = {numpy.amin(imgs[0].data)}, max = {numpy.amax(imgs[0].data)}')

**Comment by joelvbernier** [comment]
Yeah, just saw this myself with some Pilatus data.  Working a fix!

**Comment by joelvbernier** [comment]
interestingly, the Eiger is loaded via Fabio, so I'll check with them.  The 'native' format for images once loaded in the program is `float32`, so we should be able to enforce better behavior with negative pixel values.

**Comment by agshabalin** [comment]
Yes, fabio also decodes those -1 as  4294967295.

**Comment by joelvbernier** [comment]
Anatoly:

There is actually a `dtype` option in the `image-files` adapter for `imageseries'.  For a test Pilatus image (tiff in this case), I can get the proper values:

The yaml spec:
```
image-files:
  directory: ./
  files: lab6-11-10-2021_PIL10_003_000.tiff
meta: {}
options:
  dtype: int32
  empty frames: 0
  max-frames: 0
```
and the result when loading:
```
In [113]: imgs = imageseries.open('test_config.yml', 'image-files')

In [114]: np.min(imgs)
Out[114]: -2

In [115]: np.max(imgs)
Out[115]: 1100174
```
[Archive.zip](https://github.com/HEXRD/hexrd/files/7530313/Archive.zip)

**Comment by joelvbernier** [comment]
We are working on cleaning up the import formats in the GUI, but this at least will let you load them properly directly using imageseries.

@donald-e-boyce and @bnmajor -- we might need to revisit the options we feed the `image-files` adapter in the GUI...
