### ISSUE TITLE
Multithread/multiprocess eta omega map generation

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrd#39]
I believe that is done in [hexrd.instrument.extract_polar_maps()](https://github.com/HEXRD/hexrd/blob/4ad3e965d55b5402f9c8f29549f8bc92fe48e7de/hexrd/instrument.py#L662-L664).

@cjh1

**Comment by joelvbernier** [comment]
I tested it yesterday and seems kosher.  Will merge when confirmed!

**Comment by joelvbernier** [comment]
This was merged in #41,correct @cjh1 ?

**Comment by cjh1** [comment]
Yes
