### ISSUE TITLE
xrdutil._filter_hkls_eta_ome

### ISSUE THREAD

**Issue by darrencpagan** [HEXRD/hexrd#392]
Hi,

Can _filter_hkls_eta_ome be updated to also output the maskAngs list that is generated as part of the filtering process.

Thanks,
Darren

**Comment by joelvbernier** [comment]
Generally speaking, _methods aren't really many to be called outside the module they're defined in, and changing the call API can be a pain...  I assume you are talking about the eta ranges computed from the `mask` property in the helm config?  Those are available directly from the HEDM config object, _e.g._ for `mask: 5`
```
In:  cfg.find_orientations.eta.range
Out: array([[-85.,  85.],
            [ 95., 265.]])
```
