### ISSUE TITLE
Add optional text labels to Laue overlays

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#411]
This is actually a long overdue feature.  Wee need a toggle on the laue overlay manager to add [hkl] labels to the spots displayed.  @psavery, below is some example code where I was adding the labels to the cartesian plot where `fit_hkl` is just the (3, n) array of signed [hkl] from the Laue simulation.  The associated coordinates for each plot type are the same as the plots, and the `delta` is an offset parameter I fiddles with to adjust label positions (might be worths exposing in a `QScientificSpinBox`

```
fig4, ax4 = plt.subplots(1, 1, figsize=(12, 12))
ax4.imshow(img, cmap=cmap, vmin=vmin, vmax=vmax, interpolation='none')
ax4.hold(True)

ax4.plot(col_idx_used, row_idx_used, 's', mfc='none', mec='c', mew=2, ms=8)
ax4.plot(col_idx_excl, row_idx_excl, 's', mfc='none', mec='m', mew=2, ms=8)

delta=6
use_tex = False
for ihkl in range(sum(new_idx)):
    if use_tex:
        hkl_str = r"$\mathbf{(}\;\!$"
        for s in fit_hkl[:, ihkl]:
            if s < 0:
                hkl_str += r"$\mathbf{\bar{%d}}\;$" %abs(s)
            else:
                hkl_str += r"$\mathbf{%d}\;$" %s
        hkl_str += r"$\!\mathbf{)}$"
    else:
        hkl_str = "(%d,%d,%d)" % tuple(fit_hkl[:, ihkl])
    ax4.text(col_idx[ihkl]+2*delta, row_idx[ihkl]+2*delta, 
             hkl_str, 
             color='white', size=10, weight='bold')

ax4.axis('tight')
```

**Comment by joelvbernier** [comment]
Adding to this: can we also add a selector to show _either_ hkl or the associated spot energy?

**Comment by psavery** [comment]
Sure!
