### ISSUE TITLE
Refactor HEDM functionality

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#427]
We would like to create a `HEDM` package to house all HEDM-specific packages/modules.  The most logical place for this the root level of the repo.

- [ ] Collect the ff-HEDM workflow modules
  - the `config` pakckage, as it is ff-HEDM specific at the moment
  - the `cli` package (ditto)
  - `findorientations.py` 
  - `fitgrains.py`
  - `hexrd.xrdutil.nf-hedm`
  - `hexrd.grainmap`
- [ ] Generalize the `config` and `cli` packages to include nf-specific options
  - *NOTE*: this is trigger a new API and version number increment 
- [ ] Split of tomography utils in their own subpackage.

**Comment by ZackAttack614** [comment]
We are refactoring all of hexrd at the moment. We can revisit further changes beyond version 1.0 in the future.
