### ISSUE TITLE
Add filtering option to ProcessedImageSeries

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#43]
@donald-e-boyce -- looks like it would be useful to add the option to run additional filtering on raw data, primarily convuloution with a [Laplacian of Gaussian filter](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.gaussian_laplace.html).  We could add the option `'filter_gaussian_laplace'` and the arg would be the FWHM.  This could be really helpful for fine-grained data.  One issue is that it likely converts to float, but I am fine with the results being float32 anyhow (as we previously discussed).  I can get this started unless you have the bandwidth to quickly get this in.

**Comment by joelvbernier** [comment]
@donald-e-boyce : is there a way to do this with eh `addop` class method?  Before I start monkeying around in your code, I figured I would ask how best to add a new option...  :-)

**Comment by donald-e-boyce** [comment]
The easiest way is to just write a function that does what you want and then use addop to add it to the imageseries. The function should take and image and options, e.g. f(img, opts). Then you can add it to the imageseries.

```
def gauss_laplace(img, sigma);
    return scipy.ndimage.gaussian_laplace(img, sigma)

ims.addop("gaussian_laplace", gauss_laplace)
```

Then you can use it. I would suggest using this way until you're happy with it, and then we could make it built-in.

**Comment by joelvbernier** [comment]
Ok; in the above ims is a `ProcessedImageSeries` instane, correct?

**Comment by donald-e-boyce** [comment]
That's right.

**Comment by joelvbernier** [comment]
@bnmajor and @cjh1 -- looks like we already have an issue for this.  Given that we are going to at the very least going to need a Gauss-Laplace filter for nf-HEDM, I propose that we actually add the filter as a standard option to `hexrd.imageseries.process`.  Thoughts @donald-e-boyce?
