### ISSUE TITLE
Add exception handling for length 0 imageseries

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#45]
@donald-e-boyce -- I noticed some time ago that exceptions don't get passed out for IOErrors inside imageseries.  Rather, you get an imageseries with length 0.  Can you catch this and raise a RuntimeError?

**Comment by donald-e-boyce** [comment]
I am thinking the easiest thing to do is to modify imageseries.open() to
check for a length zero array.

I don't see where we catch any IOErrors, maybe fabio does something with
them. Is this just for the "image-files" format?

**Comment by donald-e-boyce** [comment]
See PR #49

**Comment by joelvbernier** [comment]
I think this is unique to the image-
files adapter.

**Comment by joelvbernier** [comment]
merged.
