### ISSUE TITLE
Multiprocessing RuntimeError in "calibrate_from_powder"

### ISSUE THREAD

**Issue by TimothyJHLong** [HEXRD/hexrd#451]
When running the script "calibrate_from_powder.py" in the current release of HEXRD, I encounter the following error:

```
File "/opt/anaconda3/envs/hexrd3ide/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

The full traceback is fairly long, so I've attached it in the file "Multiprocessing_RuntimeError.docx".  I also attached the output of `conda list` for the current env in the second attached file.

I've encountered this error on both Windows 10 and macOS Monterey Version 12.0.1 (21A559), so it does not appear to be OS specific.  The error also occurs when using the latest pre-release of HEXRD on macOS (haven't test the pre-release on Windows).

Calibrating using the HEXRD GUI does not encounter this error, but the projects I'm using HEXRD for require customizing the calibration process, which is why I'm trying to use the script.

[Multiprocessing_RuntimeError.docx](https://github.com/HEXRD/hexrd/files/8958773/Multiprocessing_RuntimeError.docx)
[conda_list_hexrd3ide.docx](https://github.com/HEXRD/hexrd/files/8958784/conda_list_hexrd3ide.docx)

Update: I tested the script with the current (as of 2022/6/22) releases of hexrd and hexrdgui on Linux (only changing file paths as needed) and *did not* encounter the error, so the error may be OS dependent.

Update 2: I'm not sure why this happened to me on macOS, but it seems to be a known issue on Windows that is completely unrelated to HEXRD.  Adding "if __name__ == '__main__':" is supposed to fix it on Windows, from what I've found.  Sorry for making an erroneous bug report.

**Comment by psavery** [comment]
@TimothyJHLong Yes that's right. If spawn multiprocessing is used (which is the default on Windows and for newer versions of Python on Mac), then a script has to be protected via:
```
if __name__ == '__main__':
    freeze_support()
    ...
```

Because when the multiprocessing part of the code is encountered, new processes will be generated that import the main script, and if there isn't a `freeze_support()` guard, this will result in an infinite recursion (each new process will also generate new processes, and each of those will generate new processes, etc.).
