### ISSUE TITLE
Issues making Pull Request

### ISSUE THREAD

**Issue by darrencpagan** [HEXRD/hexrd#494]
Tried making a pull request yesterday to fix a bug in handling of tomography masks in the process_nf.py script and received an error during the compliance check. I only changed ~ 5 lines of code with no dependency changes. Not sure what the error is or how to resolve it.

![image](https://user-images.githubusercontent.com/7535678/214589656-debe33a2-9822-4ea5-818c-0db8814e485d.png)

**Comment by psavery** [comment]
Hi @darrencpagan. Yeah, there was a change to the `pycifrw` package that started causing issues for the Mac CI. I have a fix for it in a couple of the other PRs. I'll go ahead and apply that fix to the `master` branch and rebase #492 to fix it.

**Comment by psavery** [comment]
Okay, that fix is now in master. And I went ahead and merged your PR since the CI doesn't run that script anyways.
