### ISSUE TITLE
How to set NF parameter for APS NF data set?

### ISSUE THREAD

**Issue by swrlee** [HEXRD/hexrd#538]
Hello,

We are working in reconstruction NF HEDM data from APS.
But I have problems of NF reconstruction.
I changed these parameter in process_nf.py file because APS NF data has low beam stop position.
beam_stop_y_cen = -1.48  # mm, measured from the origin of the detector paramters
or
y center translation at retina.yml file
But NF reconstruction still doesn't work.

**Comment by psavery** [comment]
Hi @swrlee! Sorry I did not get back to you earlier - I was at a conference.

I see the issue is now closed, though. Let us know if you run into further issues.
