### ISSUE TITLE
Convolution lib no longer built

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrd#54]
The following commit:

commit 4680bdb44c087561823e82dde9c3cdeafbf7a9df
Author: Saransh <saransh1@llnl.gov>
Date:   Mon Oct 21 16:34:51 2019 -0700

    trimmed the EMsoft package by a fair amount. Still needs to be looked at more carefully.
    Using package model so each module can be imported.
    setup.py still needs to be made more general for everyone to use.

Removed our hexrd/extensions/__init__.py

**Comment by joelvbernier** [comment]
Think we (you) fixed this, yes @cjh1 ?
