### ISSUE TITLE
Is xy_to_gvec Functional?

### ISSUE THREAD

**Issue by ZackAttack614** [HEXRD/hexrd#566]
https://github.com/HEXRD/hexrd/blob/bf02efcefa263b8ec7942eb8f67d64798c7b2ec7/hexrd/transforms/new_capi/xf_new_capi.py#L114-L146

Does this function work? The variable `xy_det` on line 142 doesn't seem to be defined. Are we using this at all? If not, can we remove it? If so, are there tests we can run against this, to diagnose and resolve the problem?

**Comment by psavery** [comment]
In the `xf_new_capi.py` file, the only functions that are being used are the ones listed [here](https://github.com/HEXRD/hexrd/blob/bf02efcefa263b8ec7942eb8f67d64798c7b2ec7/hexrd/transforms/xfcapi.py#L33-L38). While rewriting the transforms modules, you can compare test input/output to any functions in the `xfcapi.py` file in that hyperlink.

That whole `xf_new_capi.py` file was copied over from Oscar's transforms module updates [here](https://github.com/ovillellas/xrd-transforms). But we have only so far used the functions listed in the first link. We can get rid of any unused ones if you are replacing them with other ones.

**Comment by ZackAttack614** [comment]
Thank you Patrick. I'll mark this as closed.

**Comment by psavery** [comment]
No problem. We copied over the whole thing from Oscar's repository and were planning to transition functions from the old API to the new API as needed. But we have only ported over a few (the ones that showed the biggest performance improvements). I guess the plan now is for you to replace both the old API and new API versions with the new C++ versions.
