### ISSUE TITLE
no inverse_distortion hexrd.extensions

### ISSUE THREAD

**Issue by donald-e-boyce** [HEXRD/hexrd#586]
hexrd.extensions.inverse_distortion is referenced below but does not exist.
https://github.com/HEXRD/hexrd/blob/5f742ea99f403bb2a7b5079d0497ca284c801143/hexrd/distortion/ge_41rt.py#L12

**Comment by ZackAttack614** [comment]
@donald-e-boyce How are you running this? Have you pulled the repo, or did you install this via conda? If you pulled the repo, did you run the setup.py file, or run the make file located in the CPP subdirectory in the transforms module?

**Comment by donald-e-boyce** [comment]
Oh thanks.  I  built it recently (yesterday I think)  but before that pull
request.  So I have to rebuild.  I'll do that.

**Comment by donald-e-boyce** [comment]
Building from scratch, it failed due to not finding pybind11. I am running the development version in the instructions. It failed on the command: 
```
CONDA_BUILD=1 pip install --no-build-isolation --no-deps -U -e hexrd-dev/
```

Here is the error:
```        File "/Users/deboyce/miniconda3/envs/hexrd-dev/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
      ModuleNotFoundError: No module named 'pybind11'
      [end of output]
```

After I installed pybind11 with conda, it built successfully and the hexrd command line comes up.

**Comment by psavery** [comment]
I can fix this later
