### ISSUE TITLE
extension modules

### ISSUE THREAD

**Issue by saransh13** [HEXRD/hexrd#6]
setup.py doesn't place extension modules (sglite and transforms in the hexrd3/hexrd/extensions folder. importing package fails when user is in the hexrd3 folder. Extension modules are in the build folder so works fine otherwise.

**Comment by joelvbernier** [comment]
In general you shouldn’t run the package from inside the repository Because of the way import paths work in python. But I’ll look into making sure the Pats are set up correctly. When I have done my builds, the *.so seem to end up in the extensions folder.

**Comment by joelvbernier** [comment]
@saransh13 looks like this is now obsolete... closing issue.
