### ISSUE TITLE
Check if compile args are being used by Windows

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrd#612]
These [compile arguments](https://github.com/HEXRD/hexrd/blob/81bc56155c4a8d754bad578841a13fab35a82db9/setup.py#L118-L119) are in a gcc-like format. But it looks like they are also being passed to the Visual Studio compiler. I have a feeling that Visual Studio might just be ignoring them. We should verify that Visual Studio is using these compiler arguments correctly.

**Comment by kevindlewis23** [comment]
They are ignored, I saw this in the pip install output
```
  cl : Command line warning D9002 : ignoring unknown option '-O3'
  cl : Command line warning D9002 : ignoring unknown option '-shared'
  cl : Command line warning D9002 : ignoring unknown option '-std=c++14'
  cl : Command line warning D9002 : ignoring unknown option '-funroll-loops'
```

**Comment by psavery** [comment]
Yeah, I think we need to branch the logic for compiler options so Windows will only receive what it will actually use
