### ISSUE TITLE
Potentially Unused Function plot_ori_map

### ISSUE THREAD

**Issue by ZackAttack614** [HEXRD/hexrd#657]
The [variable `roi`](https://github.com/HEXRD/hexrd/blob/d57ef03b96abb1c9536d41add40f84606c63dd49/hexrd/grainmap/nfutil.py#L1480) is undefined in this function. This leads me to believe that the function has never been used, and probably won't be.

Consider deletion.

**Comment by psavery** [comment]
They probably meant `rotations` instead of `rot`. Since this is in `grainmap`, [this comment](https://github.com/HEXRD/hexrd/issues/658#issuecomment-2200615822) applies as well.

**Comment by psavery** [comment]
I think this was fixed in #631.
