### ISSUE TITLE
Replace Custom Memoize with functools.lru_cache Decorator

### ISSUE THREAD

**Issue by ZackAttack614** [HEXRD/hexrd#665]
The custom [Hexrd `memoize` decorator](https://github.com/HEXRD/hexrd/blob/fb05f8c81346e461a3ee80a75a8deb016a03eedc/hexrd/utils/decorators.py#L27-L95) should be removed and replaced with the built-in [`functools.lru_cache`](https://docs.python.org/3/library/functools.html#functools.lru_cache). Places where [`memoize` is being used](https://github.com/HEXRD/hexrd/blob/fb05f8c81346e461a3ee80a75a8deb016a03eedc/hexrd/instrument/detector.py#L44-L45) to create private functions should be removed, as this is unnecessary practice.

**Comment by psavery** [comment]
The `functools.lru_cache` cannot handle numpy arrays, whereas the hexrd memoize can. Numpy arrays are commonly used in the hexrd memoize places.

**Comment by ZackAttack614** [comment]
How often do we get a cache hit? Are we hitting the memoized functions with the exact same array multiple times?

**Comment by psavery** [comment]
It's pretty common, but may be more common when hexrdgui is using the library than hexrd by itself. For example, this [`pixel_solid_angles`](https://github.com/HEXRD/hexrd/blob/b8050c6bf8ae5ddb9693a732acf762b53b81a6c7/hexrd/instrument/planar_detector.py#L231-L232) is very time-consuming and called multiple times in certain situations.

We can potentially refactor the memoization to work differently. For example, cache the result in the `PlanarDetector` class itself, and if any of the parameters used by it are modified on the detector class, invalidate that cache. But I'm not certain that would be cleaner.

We can rethink some of the memoization structure.

**Comment by ZackAttack614** [comment]
Ah, of course, the GUI makes sense for there to be many cache hits. Thanks for explaining this, I'll close this issue.
