### ISSUE TITLE
Remove or reassign old entry point for GUI

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#67]
The CLI entry point for the GUI (`hexrd gui`) is still in the repo, but currently doesn't do anything.  We should probably map it to the `hexrdgui` executable, and have it raise an exception if not installed.  Thoughts @cjh1 and @johnkit ?

**Comment by cjh1** [comment]
@joelvbernier I can take a look at this.

**Comment by cjh1** [comment]
I think the best plan is just to remove the entry point entirely, I think keep the to separate makes the most sense. I will push PR that does this.
