### ISSUE TITLE
Potentially Broken Method - unitcell.CalcAnomalous

### ISSUE THREAD

**Issue by ZackAttack614** [HEXRD/hexrd#683]
The method [`unitcell.CalcAnomalous`](https://github.com/HEXRD/hexrd/blob/b6ae69fe20fca1f6cf48235cbeeb65d98bc8f6b5/hexrd/material/unitcell.py#L790-L791) references `self.f1` and `self.f2`, which are not defined. I suspect that this means the method isn't being used - if that isn't the case, it should be fixed.

Please advise.

**Comment by psavery** [comment]
@saransh13
