### ISSUE TITLE
Some methods defined in both transforms and rotations.py

### ISSUE THREAD

**Issue by kevindlewis23** [HEXRD/hexrd#692]
There are some functions in transforms (hexrd/transforms/xf.py and hexrd/transforms/xfcapi.py) like mapAngle, rowNorm, columnNorm, angularDistance, quatProductMatrix, unitVector, and arccosSafe that are also defined in rotations.py.  Do people use these methods from both places?

Either this should only be in one place, or the implementation in one place should just be an alias of the other.  If the second option is better, where should the main implementation live?

**Comment by kevindlewis23** [comment]
Also `material/symbols.py` and `material/spacegroup.py` have the same 1000+ line _hallStr, and then _buildDict which builds a dictionary from the string.

**Comment by psavery** [comment]
I'd say that when there are duplicated functions, we can definitely eliminate one of the duplicated functions. If we are concerned that users may be importing the duplicated function from the module where it was deleted, it can still be imported within that module to maintain backward compatibility.

**Comment by kevindlewis23** [comment]
One of the biggest offenders seems to be the `hexrd/wppf` directory.  `peakfunctions.py` is unsurprisingly very similar to `hexrd/fitting/peakfunctions.py`.  There are some functions that are exactly the same, and there are some that are the exact same but then one implementation normalizes the output. `hexrd/wppf/phase.py` has a bunch of classes that share a bunch of methods and exact implementations, which could easily be replaced by extending a base class.
