### ISSUE TITLE
error on polar warp

### ISSUE THREAD

**Issue by adas42** [HEXRD/hexrd#726]
I am running powder integrations on hexrd 0.9.6 and gerring the following error trying to do a polar warp. Same function however works ok with a late 2023 release. Thoughts?

(powder) [ad785@f2-analysis-2 scripts]$ python integrate_powder.py
loading instrument
reading images from ff1
found 2 frames on ff1
reading images from ff2
found 2 frames on ff2
reading darkfields from ff1
found 2 darkfield frames on ff1
reading darkfields from ff2
found 2 darkfield frames on ff2
done reading files, averaging and subtracting darkfield
Traceback (most recent call last):
  File "/nfs/chess/aux/reduced_data/cycles/2024-1/id3a/balila-3970-a/scripts/integrate_powder.py", line 235, in <module>
    pimg = pv.warp_image(img_dict, pad_with_nans=True, do_interpolation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/chess/opt/anaconda3_ad785/envs/powder/lib/python3.11/site-packages/hexrd/projections/polar.py", line 259, in warp_image
    this_img = panel.interpolate_bilinear(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/chess/opt/anaconda3_ad785/envs/powder/lib/python3.11/site-packages/hexrd/instrument/detector.py", line 985, in interpolate_bilinear
    is_2d = img.ndim == 2
            ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ndim'

**Comment by psavery** [comment]
Can you send me your `integrate_powder.py` script? Or tell me where it's located on CLASSE?

It looks like `img` is `None`, which might mean the `img_dict` provided to `pv.warp_image()` has an image that is `None`? That's just a guess, though.

**Comment by adas42** [comment]
> Can you send me your `integrate_powder.py` script? Or tell me where it's located on CLASSE?
> 
> It looks like `img` is `None`, which might mean the `img_dict` provided to `pv.warp_image()` has an image that is `None`? That's just a guess, though.

Here's the location, thanks!: /nfs/chess/aux/reduced_data/cycles/2024-1/id3a/balila-3970-a/scripts/integrate_powder.py

**Comment by psavery** [comment]
I looked at your script! It looks like the `img_dict` that is being input into `pv.warp_image()` contains a mixture of monolithic keys (`ff1`, `ff2`) and composite keys (`ff1_0_0`, `ff1_0_1`, ...), and the composite keys have a value of `None`.

I think the lines right above that are the issue:

```python
img_dict['ff1'] = image_int_out1
img_dict['ff2'] = image_int_out2
```

If you're running with a composite instrument, you'll need to break up the images instead. It might be easiest to do it with an imageseries, but here's how you can do it manually:

```python
for det_key, panel in instr.detectors.items():
    if det_key.startswith('ff1'):
        img = image_int_out1
    else:
        img = image_int_out2

    img_dict[det_key] = img[panel.roi[0][0]:panel.roi[0][1], panel.roi[1][0]:panel.roi[1][1]]
```

In fact, I apparently had the ability to modify that script, so I commented out the old lines and added those lines instead. Let me know if it works for you! It appeared to be running for me...

**Comment by adas42** [comment]
I just tested it out. This works, thanks a lot!
