### ISSUE TITLE
Update WPPF to accept data directly rather than just filenames

### ISSUE THREAD

**Issue by cjh1** [HEXRD/hexrd#98]
This is needed for HEXRDGUI integration

**Comment by joelvbernier** [comment]
@saransh13 -- what about this one?  If it is closed, can you link the relevant PR(s) and close it out?

**Comment by saransh13** [comment]
Yeah this was closed a while ago. I’ll link the relevant PR.

**Comment by saransh13** [comment]
Fixed via https://github.com/HEXRD/hexrd/pull/100
